[package]
name = "goscript-engine"
version = "0.1.0"
authors = ["oxfeeefeee <pb01005051@gmail.com>"]
edition = "2021"

[dependencies]
slotmap = "0.4"
time-test = "0.2.2"
futures-lite = "1.12.0"
sprintf = "0.1.2"

[dependencies.goscript-parser]
path = "../parser"
version = "0.1.0"

[dependencies.goscript-vm]
path = "../vm"
version = "0.1.0"

[dependencies.goscript-types]
path = "../types"
version = "0.1.0"

[dependencies.goscript-codegen]
path = "../codegen"
version = "0.1.0"

[dependencies.goscript-pmacro]
path = "../pmacro"
version = "0.1.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "leet5_benchmark"
harness = false

[features]

